## Prod profile, only loads this file when on production
spring:
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    datasource:
        url: "${SPRING_DATASOURCE_URL}"
        username: "${SPRING_DATASOURCE_USERNAME}"
        password: "${SPRING_DATASOURCE_PASSWORD}"
    config:
            activate:
                on-profile: prod
