## Dev profile, only loads this file when on development
spring:
    datasource:
        url: jdbc:h2:mem:virtual
        username: root
        password: root
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update

    h2:
        console.enabled: true
        console.path: /h2-console
        console.settings.trace: false
        spring.h2.console.settings.web-allow-others: false
    config:
        activate:
            on-profile: dev

