##Default application.yml file, always loads this
server:
  port: 8082
spring:
  spring:
    profiles:
      include: default
  mvc:
    converters:
      preferred-json-mapper: gson
  application:
    name: TWEETAPI
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
