server:
    port: 8081
spring:
    mvc:
        converters:
            preferred-json-mapper: gson
    application:
        name: AuthenticationAPI
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    datasource:
        url: "jdbc:mysql://localhost:3306/tweets"
        username: "root"
        password: "root"

