  server:
    port: 8080
  spring:
    mvc:
      converters:
        preferred-json-mapper: gson
    application:
      name: TWEETAPI
    jpa:
      database: mysql
      hibernate:
        ddl-auto: update
    datasource:
      url: "jdbc:mysql://localhost:3306/users"
      username: "root"
      password:
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8083/eureka
